### ISSUE TITLE
"Library not loaded" when registering dll

### ISSUE THREAD

**Issue by madwyn** [steveschow/osxwineasio#1]
Hi Steve,

Thank you very much for your binary build and repository.

I'm having a problem when trying to run `wine regsvr32 wineasio.dll`. The full error message is as below:

``` bash
$ wine regsvr32 wineasio.dll
err:module:load_builtin_dll failed to load .so lib for builtin L"wineasio.dll": dlopen(/usr/local/Cellar/wine/1.7.34/lib/wine/wineasio.dll.so, 258): Library not loaded: /usr/local/lib/libjack.0.dylib
  Referenced from: /usr/local/Cellar/wine/1.7.34/lib/wine/wineasio.dll.so
  Reason: no suitable image found.  Did find:
    /usr/local/lib
regsvr32: Failed to load DLL 'wineasio.dll'
```

I'm using `brew` for the package management, so I installed `jack` using `brew install jack`. I can find that `libjack.0.dylib` does exist in `/usr/local/lib/`.

I have googled for a while, but no working clue yet.

Would you please help me with this, thank you very much!

**Comment by steveschow** [comment]
sorry this is such a late reply, I didn't see this until now.  

I recommend you use JackOSX, not the brew version.  

I also recommend you use Wine.app rather then using brew for wine, but it should work with the brew'd wine also.  The message you have above shows you don't have wine properly setup on your system.  I recommend you try using the instructions from my read me, should work fine!
