### ISSUE TITLE
Request: build latest version of wineasio?

### ISSUE THREAD

**Issue by DanielBielak** [steveschow/osxwineasio#2]
Hi.

Will you please build for macOS (Mojave) the latest version of wineasio (as it is compatible with versions > 6.5 of Wine)?

https://github.com/wineasio/wineasio/releases

Thank you.

Sincerely,
Daniel Bielak

**Comment by steveschow** [comment]
I haven't used this in quite some time ever since I moved to newer versions of MacOS that don't really support wine very well.
